name: Build & Deploy HTML Project

on:
  push:
    branches:
      - master   # change to 'main' if your branch is main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Building HTML project"

      - name: Deploy to local folder
        run: |
          mkdir "C:\Users\user\Desktop\CI Deployment"
          xcopy "C:\Users\user\Desktop\CI Practice\*" "C:\Users\user\Desktop\CI Deployment" /E /I /Y
          echo "Deployment completed"
